stages:
  - build
  - sync

# Build and Test Job
build_and_test:
  stage: build
  image: maven:3.8.5-jdk-11
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: always
  script:
    - echo "Running Maven build and tests for MR to dev..."
    - mvn -B -U clean install
  cache:
    paths:
      - .m2/repository

# Sync to GitHub Job
sync_to_github:
  stage: sync
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    - git config --global user.email "s.suresh.gaikar@accenture.com"
    - git config --global user.name "sgaikar"
    - git checkout -b dev
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/ShubhangiGaikar25/mda-poc.git
    - git fetch github dev || true  # Fetch latest from GitHub
    - git merge github/dev --allow-unrelated-histories -m "Merge GitHub dev into GitLab dev before push" || true
    - git push github dev:dev