stages:
  - sync

sync_to_github:
  stage: sync
  only:
    - dev
  script:
    - git config --global user.email "s.suresh.gaikar@accenture.com"
    - git config --global user.name "sgaikar"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/ShubhangiGaikar25/mda-poc.git
    - git push github dev:dev
